---
title: "Databases Webscraping"
author: "Raissa Philibert"
date: "October 18, 2019"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```


```{r libraries}
# https://github.com/ropensci/fulltext
library(fulltext)
library(pubchunks)
library(tidyverse)
library(magrittr)
library(dplyr)
library(purrr)
library(here)

```

```{r API keys}
Sys.setenv(ELSEVIER_SCOPUS_KEY = '3da3a9477a6e0a7fefc0bbfb49f288f5', SPRINGER_KEY = 'dc293398c185c33d930865ae1fd6eae3', ENTREZ_KEY = "1621b309cd4dab23f28c432d4e7baa76d909" )

```

```{r webscrape genbank}

databaseList <- ft_search_ls()
databaseList <- databaseList[!databaseList %in% c("bmc","scopus","entrez")]

# ft_links() - get links for articles (xml and pdf).
resFound <- NULL

st <- "Genbank"
st <- "bioinformatics databases"
res1 <- ft_search(query = st, from = databaseList, limit = 10)

for(nm in names(res1)){
  Found <- res1[[nm]][["found"]]
  if(!is.null(Found)){
  resFound <- bind_rows(resFound,data.frame(db=nm,found=Found,searchTerm=st))}
}

links <- map(ft_links(res1),`[[`,"ids")

cross <- ft_get(links$crossref)
x <- map(links,ft_get)

y <- map(x,ft_collect)

hold <- map(y, get_columns)

get_columns <- function(collect){
  collect %>%
  ft_collect() %>% 
  pub_chunks(c("doi", "refDois", "history", "journal_meta", "publisher", "author", "aff", "title", "keywords", "abstract")) %>%  
  pub_tabularize() -> h
  # .$elife
}


```



```{r standardFormat}

raw <- map_dfr(hold,extract_hold)

extract_hold <- function(data){
  df_raw <- NULL
  for (nm in names(data)){
    
    df_raw <- bind_rows(df_raw, map_df(data[[nm]], `[`))
    
  }
  
  df_raw
}


df <- data.frame(doi=character(),
                 refDois=character(),
                 Year=numeric(),
                 Journal=character(),
                 Author=character(),
                 Institution=character(),
                 Title=character(),
                 Keywords=character(),
                 Abstract=character())

```

```{r save}

write.csv(df_raw, here("/data/YourName-YourTopic.csv"))

```


