---
title: "FullTextWorkflow_LuciaDiana"
author: "Lucia Darrow"
date: "October 18, 2019"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```


```{r libraries}
# https://github.com/ropensci/fulltext
library(fulltext)
library(pubchunks)
library(tidyverse)
library(magrittr)
library(dplyr)
library(purrr)
library(here)
library(lubridate)

```

```{r import}

searchTerms <- read.csv(here("/raw-data/SearchTerms.csv"))
searchTerms$Term %<>% as.character()
searchTerm = 'sequence alignment'
```

```{r webscrape genbank}

databaseList <- ft_search_ls()
databaseList <- databaseList[!databaseList %in% c("bmc","scopus", "entrez")]

# ft_links() - get links for articles (xml and pdf).
resFound <- NULL

st <- "Genbank"
st <- "Sanger sequencing"
for(st in searchTerms$Term) {
  
  res1 <- ft_search(query = st, from = databaseList, limit = 10)
  
  for(nm in names(res1)){
    Found <- res1[[nm]][["found"]]
    if(!is.null(Found)){
      resFound <- bind_rows(resFound,data.frame(db=nm,found=Found,searchTerm=st))}
  }
  
}

resFoundGrp <- resFound %>% group_by(searchTerm) %>% summarise(found = sum(found)) %>% arrange(found)

mylinks <- ft_links(res1)$plos$ids

# ft_get() - get full or partial text of articles.
x <- ft_get(mylinks)


x %>% ft_collect() %>% 
  pub_chunks("publisher") %>% 
  pub_tabularize()

x %>%
  ft_collect() %>% 
  pub_chunks(c("doi", "refDois", "history", "journal_meta", "publisher", "author", "aff", "title", "keywords", "abstract")) %>%  
  pub_tabularize() -> hold
  # .$elife

```


```{r standardFormat}

df_raw <- NULL
for (nm in names(hold)){
  
  df_raw <- bind_rows(df_raw, map_df(hold[[nm]], `[`))
  
}

# Create simplified DF for analysis
df_raw_refined <- df_raw[, which(colSums(is.na(df_raw)) < 200)]
df_raw_refined %<>% select(-c("history.received", "journal_meta.journal.id", "journal_meta.journal.id.1", "journal_meta.journal.id.2", "journal_meta.issn", "journal_meta.publisher", ".publisher" )) %>%
  unite(col = author1, c(authors.surname, authors.given_names), sep = ", ") %>%
  mutate(Year = year(history.accepted), history.accepted = NULL) %>%
  rename("affiliation" = "aff.addr.line") %>%
  rename("journal" = "journal_meta.journal.title.group") %>%
  select(-starts_with("authors.")) %>% 
  select(-starts_with("aff.")) 
  
df <- data.frame(doi=character(),
                 refDois=character(),
                 Year=numeric(),
                 Journal=character(),
                 Author=character(),
                 Institution=character(),
                 Title=character(),
                 Keywords=character(),
                 Abstract=character())

```

```{r save}

write.csv(df_raw, here("/data/YourName-YourTopic.csv"))

```


