---
title: "General Visualizations"
author: "Jasmine Lai and Diana Lin"
date: "20/10/2019"
output: 
  html_document:
    toc: true
---
```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = FALSE, message = FALSE, warning = FALSE, fig.width=12, fig.height=8)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(plotly)
library(cowplot)
library(tidyverse)
library(gganimate)
library(fulltext)
```

```{r searchterms, include=FALSE}
search <- read_csv("../raw-data/SearchTerms.csv")
```

```{r, include=FALSE}
dist_t <- search %>% 
  group_by(Topic) %>% 
  summarise(`total terms` = n())

n_topic <- nrow(dist_t)
```

```{r webscrape db, include = FALSE}
databaseList <- ft_search_ls()
databaseList <- databaseList[!databaseList %in% c("bmc","scopus","entrez")]
n_db <- length(databaseList)
```

## Bioinformatic Topics
We have identified `r n_topic` major topics in Bioinformatics. Within each topic we used up to 3 search terms in `r n_db` databases of scientific articles.
```{r load  all webscraping data, include = FALSE}
df_all <- read_csv("../data/AllWebscrape.csv")
```

```{r load sequencing data, include=FALSE}
# Load data for all 7 sequencing types
seq_spec <- read_csv("../data/sequencing-specific.csv")
```

## Racing Bar Graphs
```{r cleaning up data, include=FALSE}
seq_data <- seq_spec %>% 
  filter(topic != "NGS",
         topic != "third-generation sequencing",
         topic != "ont reads sequencing") %>%
  mutate(topic = str_replace(topic, " sequencing","")) %>% 
  group_by(topic, Year) %>% 
  summarise(total = n()) %>% 
  mutate(cum_total = cumsum(total)) %>% 
  ungroup()
```

```{r ordering racing bars, include = FALSE}
ordered_df <- NULL

for (yr in 2003:2019) {
  order <- seq_data %>% 
    filter(Year == yr) %>% 
    arrange(cum_total) %>% 
    mutate(ordering = row_number())
  
  ordered_df <- ordered_df %>% rbind(order)
}
```

The data is limited to the establishment of PLoS in 2003
```{r racing bars animate, echo=FALSE}
p <- ordered_df %>% 
  ggplot(aes(ordering, group = topic))+
  geom_tile(aes(y = cum_total/2,
                height = cum_total,
                width = 0.9,
                fill = topic)) +
  geom_text(aes(y = cum_total, label = topic), hjust = "left", fontface = "bold", nudge_y = 50) +
  scale_fill_viridis_d() +
  coord_cartesian(clip = "off", expand = FALSE) +
  coord_flip() +
#animate
  transition_states(Year, transition_length = 8, state_length = 4, wrap = FALSE) +
  ease_aes("cubic-in-out") +
#aesthetics
  labs(subtitle = "Trends in sequencing methods",title = "Year {closest_state}", y = "cumulative total papers") +
  theme(plot.background = element_blank(),
        legend.position = "none",
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        text = element_text(size=14),
        plot.title = element_text(size = 35)) +
  ylim(0,1300) +
  xlab("") 

#rendering the animation
animate(p, nframes = 750, 
        fps = 20, 
        end_pause = 10)
```

